// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'gemini-pdf-context-window-size-label'
  | 'gemini-pdf-new-chat-button-label'
  | 'gemini-pdf-reader-new-chat-title'
  | 'gemini-pdf-settings-title'
  | 'gemini-pdf-system-prompt-label'
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
