// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'geminipdf-gemini-pdf-context-window-size-label'
  | 'geminipdf-gemini-pdf-reader-new-chat-title'
  | 'geminipdf-gemini-pdf-settings-title'
  | 'geminipdf-gemini-pdf-system-prompt-label'
  | 'geminipdf-item-info-row-example-label'
  | 'geminipdf-item-section-example1-head-text'
  | 'geminipdf-item-section-example1-sidenav-tooltip'
  | 'geminipdf-item-section-example2-button-tooltip'
  | 'geminipdf-item-section-example2-head-text'
  | 'geminipdf-item-section-example2-sidenav-tooltip'
  | 'geminipdf-menuitem-filemenulabel'
  | 'geminipdf-menuitem-label'
  | 'geminipdf-menuitem-submenulabel'
  | 'geminipdf-menupopup-label'
  | 'geminipdf-prefs-table-detail'
  | 'geminipdf-prefs-table-title'
  | 'geminipdf-prefs-title'
  | 'geminipdf-startup-begin'
  | 'geminipdf-startup-finish'
  | 'geminipdf-tabpanel-lib-tab-label'
  | 'geminipdf-tabpanel-reader-tab-label';
