// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'askmypaper-context-window-size-label'
  | 'askmypaper-prompt-for-selection-label'
  | 'askmypaper-reader-chat-head-text'
  | 'askmypaper-reader-chat-sidenav-tooltip'
  | 'askmypaper-reader-new-chat-title'
  | 'askmypaper-settings-title'
  | 'askmypaper-system-prompt-label'
  | 'askmypaper-title-generation-model-label'
  | 'askmypaper-title-generation-prompt-label'
  | 'menuitem-filemenulabel'
  | 'menuitem-label'
  | 'menuitem-submenulabel'
  | 'menupopup-label'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'tabpanel-lib-tab-label'
  | 'tabpanel-reader-tab-label';
