// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llmProvider": string;
      "geminiApiKey": string;
      "openaiApiKey": string;
      "anthropicApiKey": string;
      "systemPrompt": string;
      "contextWindowSize": number;
      "promptForSelection": string;
      "geminiModelList": string;
      "openaiModelList": string;
      "anthropicModelList": string;
      "geminiSelectedModel": string;
      "openaiSelectedModel": string;
      "anthropicSelectedModel": string;
      "useWebSearch": boolean;
      "reasoningMode": string;
      "chatPanelHeight": number;
      "titleGenerationProvider": string;
      "titleGenerationModel": string;
      "titleGenerationPrompt": string;
      "citationRenderProvider": string;
      "citationRenderModel": string;
      "citationRenderPrompt": string;
    };
  }
}
