// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "geminiApiKey": string;
      "geminiSystemPrompt": string;
      "contextWindowSize": number;
      "promptForSelection": string;
      "geminiModelList": string;
      "geminiSelectedModel": string;
      "geminiUseGoogleSearch": boolean;
    };
  }
}
